import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { MessageSquare, Share, ThumbsUp } from "lucide-react";

export interface Post {
  id: number;
  userId: number;
  content: string;
  imageUrl?: string;
  createdAt: string;
  username: string;
  siName?: string;
}

interface PostItemProps {
  post: Post;
}

export default function PostItem({ post }: PostItemProps) {
  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleString('en-US', {
      month: 'long',
      day: 'numeric',
      hour: 'numeric',
      minute: 'numeric',
      hour12: true
    });
  };
  
  return (
    <div className="bg-white shadow rounded-lg overflow-hidden feed-transition mb-6">
      <div className="p-4">
        <div className="flex items-center space-x-3">
          <Avatar className="h-10 w-10">
            <AvatarImage 
              src="https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=256&h=256" 
              alt="User profile" 
            />
            <AvatarFallback>{post.username?.charAt(0).toUpperCase() || "U"}</AvatarFallback>
          </Avatar>
          <div>
            <h3 className="text-sm font-medium text-neutral-800">{post.username}</h3>
            <p className="text-xs text-neutral-500">
              {formatDate(post.createdAt)}
              {post.siName && ` · Via ${post.siName}`}
            </p>
          </div>
        </div>
        
        <p className="mt-3 text-sm text-neutral-800">{post.content}</p>
        
        {post.imageUrl && (
          <div className="mt-3">
            <img 
              src={post.imageUrl} 
              alt={`Post by ${post.username}`} 
              className="rounded-lg w-full"
            />
            {post.siName && (
              <p className="mt-1 text-xs text-neutral-500 italic">Image generated by {post.siName}</p>
            )}
          </div>
        )}
        
        <div className="mt-4 flex items-center justify-between">
          <div className="flex space-x-4">
            <button className="flex items-center text-neutral-600 hover:text-primary">
              <ThumbsUp className="h-5 w-5 mr-1" />
              <span className="text-sm">42</span>
            </button>
            <button className="flex items-center text-neutral-600 hover:text-primary">
              <MessageSquare className="h-5 w-5 mr-1" />
              <span className="text-sm">12</span>
            </button>
            <button className="flex items-center text-neutral-600 hover:text-primary">
              <Share className="h-5 w-5 mr-1" />
              <span className="text-sm">Share</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
